# Generated by Django 5.2.17 on 2026-09-07 17:23

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('matricule', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('job_title', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], db_index=True, default='OFFLINE', max_length=16)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('timezone', models.CharField(default='Africa/Lome', max_length=64)),
                ('segment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('avatar_id', models.UUIDField(blank=True, null=True)),
                ('ldap_dn', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('pending_approval', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.SmallIntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_uuid', models.CharField(max_length=128)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(choices=[('IOS', 'Ios'), ('ANDROID', 'Android'), ('WEB', 'Web'), ('DESKTOP', 'Desktop'), ('OTHER', 'Other')], max_length=16)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('push_token', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('last_location', models.CharField(blank=True, max_length=255, null=True)),
                ('trusted', models.BooleanField(default=False)),
                ('compromised', models.BooleanField(default=False)),
                ('jailbreak', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField()),
                ('module', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('entity_type', models.CharField(blank=True, max_length=80, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('severity', models.CharField(max_length=30)),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='iam.device')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.TextField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
            },
        ),
        migrations.CreateModel(
            name='OtpSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.BinaryField()),
                ('algorithm', models.CharField(default='SHA1', max_length=16)),
                ('digits', models.SmallIntegerField(default=6)),
                ('period', models.SmallIntegerField(default=30)),
                ('issuer', models.CharField(default='YAS Connect', max_length=64)),
                ('backup_codes', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_secret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_secrets',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_history',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('reset_channel', models.CharField(choices=[('SMS', 'Sms'), ('EMAIL', 'Email'), ('APPEL', 'Appel')], max_length=16)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_seen_visibility', models.CharField(choices=[('EVERYONE', 'Everyone'), ('CONTACTS', 'Contacts'), ('NOBODY', 'Nobody')], default='EVERYONE', max_length=16)),
                ('profile_photo_visibility', models.CharField(choices=[('EVERYONE', 'Everyone'), ('CONTACTS', 'Contacts'), ('NOBODY', 'Nobody')], default='EVERYONE', max_length=16)),
                ('online_status_visibility', models.CharField(choices=[('EVERYONE', 'Everyone'), ('CONTACTS', 'Contacts'), ('NOBODY', 'Nobody')], default='EVERYONE', max_length=16)),
                ('read_receipts_enabled', models.BooleanField(default=True)),
                ('typing_indicator_enabled', models.BooleanField(default=True)),
                ('allow_calls', models.BooleanField(default=True)),
                ('allow_mentions', models.BooleanField(default=True)),
                ('allow_group_invites', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='iam.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='iam.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='iam.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='iam.role')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_jti', models.UUIDField(db_index=True, unique=True)),
                ('refresh_jti', models.UUIDField(blank=True, null=True, unique=True)),
                ('refresh_hash', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('login_method', models.CharField(choices=[('PASSWORD', 'Password'), ('LDAP', 'Ldap'), ('SSO', 'Sso'), ('OTP', 'Otp'), ('REFRESH', 'Refresh'), ('DEVICE_LINK', 'Device Link')], default='PASSWORD', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='iam.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('jti', models.UUIDField(unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='iam.session')),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('browser', models.CharField(blank=True, max_length=64, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=32, null=True)),
                ('login_method', models.CharField(choices=[('PASSWORD', 'Password'), ('LDAP', 'Ldap'), ('SSO', 'Sso'), ('OTP', 'Otp'), ('REFRESH', 'Refresh'), ('DEVICE_LINK', 'Device Link')], default='PASSWORD', max_length=16)),
                ('success', models.BooleanField(db_index=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('INVALID_CREDENTIALS', 'Invalid Credentials'), ('ACCOUNT_PENDING', 'Account Pending'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_LOCKED', 'Account Locked'), ('RATE_LIMITED', 'Rate Limited'), ('DIRECTORY_UNAVAILABLE', 'Directory Unavailable'), ('MFA_INVALID', 'Mfa Invalid'), ('MFA_CHALLENGE_EXPIRED', 'Mfa Challenge Expired')], max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='iam.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='iam.session')),
            ],
            options={
                'db_table': 'login_history',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('timezone', models.CharField(default='Africa/Lome', max_length=100)),
                ('notification_sound', models.BooleanField(default=True)),
                ('auto_download_media', models.BooleanField(default=False)),
                ('read_receipts', models.BooleanField(default=True)),
                ('typing_indicator', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_seen'], name='devices_last_seen_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_uuid')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'action'], name='audit_module_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['old_values'], name='audit_old_values_gin'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['new_values'], name='audit_new_values_gin'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='audit_metadata_gin'),
        ),
        migrations.AddIndex(
            model_name='otpsecret',
            index=django.contrib.postgres.indexes.GinIndex(fields=['backup_codes'], name='otp_backup_codes_gin'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='pwd_reset_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_locked'], name='users_active_locked_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='users_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='users_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email'], name='users_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['username'], name='users_username_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['matricule'], name='users_matricule_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'is_active'], name='sessions_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['user', 'expires_at'], name='refresh_user_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='refresh_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', '-created_at'], name='login_hist_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email', '-created_at'], name='login_hist_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address', '-created_at'], name='login_hist_ip_created_idx'),
        ),
    ]
