# Generated by Django 5.2.17 on 2026-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('INVALID_CREDENTIALS', 'Invalid Credentials'), ('ACCOUNT_PENDING', 'Account Pending'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_LOCKED', 'Account Locked'), ('RATE_LIMITED', 'Rate Limited'), ('DIRECTORY_UNAVAILABLE', 'Directory Unavailable'), ('MFA_INVALID', 'Mfa Invalid'), ('MFA_CHALLENGE_EXPIRED', 'Mfa Challenge Expired'), ('DEVICE_COMPROMISED', 'Device Compromised'), ('DEVICE_JAILBROKEN', 'Device Jailbroken')], max_length=64, null=True),
        ),
    ]
