# Generated by Django 5.2.17 on 2026-09-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_auth_f_tos_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='reset_channel',
            field=models.CharField(choices=[('TOTP', 'Totp'), ('SMS', 'Sms'), ('EMAIL', 'Email'), ('APPEL', 'Appel')], max_length=16),
        ),
    ]
