# Generated by Django 5.2.17 on 2026-09-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_pres_a_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='voip_push_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
