# Generated by Django 5.2.17 on 2026-09-08 10:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_code', models.CharField(max_length=64, unique=True)),
                ('feature_name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.SmallIntegerField(default=100)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_platforms', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_flags',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['target_roles'], name='ff_target_roles_gin')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128, unique=True)),
                ('module', models.CharField(max_length=64)),
                ('cron_expression', models.CharField(blank=True, max_length=64, null=True)),
                ('interval_seconds', models.IntegerField(blank=True, null=True)),
                ('handler', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_jobs',
                'indexes': [models.Index(fields=['enabled', 'next_execution'], name='sched_jobs_due_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('setting_key', models.CharField(max_length=128)),
                ('setting_value', models.JSONField()),
                ('value_type', models.CharField(default='string', max_length=32)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['setting_value'], name='sys_settings_value_gin')],
                'unique_together': {('category', 'setting_key')},
            },
        ),
    ]
