# Generated by Django 5.2.17 on 2026-09-16 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0008_notif_a_voip_push_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('version', models.IntegerField(default=1)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=32)),
                ('wrapped_key', models.BinaryField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_keys',
                'indexes': [models.Index(fields=['conversation_id'], name='conv_keys_conv_idx')],
                'unique_together': {('conversation_id', 'version')},
            },
        ),
        migrations.CreateModel(
            name='IdentityKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.IntegerField()),
                ('identity_public_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_key', to='iam.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_keys',
            },
        ),
        migrations.CreateModel(
            name='OneTimePreKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.IntegerField()),
                ('public_key', models.BinaryField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_prekeys', to='iam.device')),
            ],
            options={
                'db_table': 'one_time_prekeys',
                'indexes': [models.Index(condition=models.Q(('consumed_at__isnull', True)), fields=['device'], name='otpk_device_available_idx')],
                'unique_together': {('device', 'key_id')},
            },
        ),
        migrations.CreateModel(
            name='SignedPreKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.IntegerField()),
                ('public_key', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_prekeys', to='iam.device')),
            ],
            options={
                'db_table': 'signed_prekeys',
                'indexes': [models.Index(fields=['device', '-created_at'], name='spk_device_created_idx')],
                'unique_together': {('device', 'key_id')},
            },
        ),
    ]
