# Generated by Django 5.2.17 on 2026-09-07 17:23

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('confidential', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField()),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('bucket_name', models.CharField(blank=True, default='', max_length=100)),
                ('encrypted', models.BooleanField(default=False)),
                ('compressed', models.BooleanField(default=False)),
                ('virus_scanned', models.BooleanField(default=False)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_files',
            },
        ),
        migrations.CreateModel(
            name='MediaAccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('DELETE', 'Delete'), ('SHARE', 'Share')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_access_logs', to='iam.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_access_logs', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='media.mediafile')),
            ],
            options={
                'db_table': 'media_access_logs',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail_path', models.TextField(blank=True, default='')),
                ('optimized_path', models.TextField(blank=True, default='')),
                ('original_resolution', models.CharField(blank=True, default='', max_length=50)),
                ('format', models.CharField(blank=True, default='', max_length=20)),
                ('quality', models.SmallIntegerField(default=0)),
                ('annotated', models.BooleanField(default=False)),
                ('blurred', models.BooleanField(default=False)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_detail', to='media.mediafile')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_version_changes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='media.document')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='media.mediafile')),
            ],
            options={
                'db_table': 'document_versions',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_detail', to='media.mediafile'),
        ),
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('waveform', models.JSONField(blank=True, default=list)),
                ('codec', models.CharField(blank=True, default='', max_length=30)),
                ('transcription_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_detail', to='media.mediafile')),
            ],
            options={
                'db_table': 'audio_messages',
            },
        ),
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_detail', to='media.mediafile')),
            ],
            options={
                'db_table': 'media_metadata',
            },
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('SHARED', 'Shared'), ('DOCUMENT', 'Document')], max_length=20)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('quota_bytes', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_usage',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('resolution', models.CharField(blank=True, default='', max_length=30)),
                ('codec', models.CharField(blank=True, default='', max_length=50)),
                ('thumbnail_path', models.TextField(blank=True, default='')),
                ('streaming_ready', models.BooleanField(default=False)),
                ('transcoding_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='media.mediafile')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VoiceTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('text', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='media.audiomessage')),
            ],
            options={
                'db_table': 'voice_transcriptions',
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['owner', '-created_at'], name='media_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['scan_status'], name='media_scan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['media_type'], name='media_type_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaaccesslog',
            index=models.Index(fields=['media', '-created_at'], name='media_log_media_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaaccesslog',
            index=models.Index(fields=['user', '-created_at'], name='media_log_user_at_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaaccesslog',
            index=models.Index(fields=['action', '-created_at'], name='media_log_action_at_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['media'], name='doc_ver_media_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_category_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='documents_owner_at_idx'),
        ),
        migrations.AddIndex(
            model_name='audiomessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['waveform'], name='audio_msg_waveform_gin'),
        ),
        migrations.AddIndex(
            model_name='audiomessage',
            index=models.Index(fields=['transcription_status'], name='audio_msg_transcript_idx'),
        ),
        migrations.AddIndex(
            model_name='mediametadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='media_meta_json_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='storageusage',
            unique_together={('user', 'storage_type')},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['transcoding_status'], name='videos_transcode_idx'),
        ),
        migrations.AddIndex(
            model_name='voicetranscription',
            index=models.Index(fields=['audio', '-created_at'], name='voice_tr_audio_at_idx'),
        ),
    ]
