# Generated by Django 5.2.17 on 2026-09-15 21:56

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('call_ring_enabled', models.BooleanField(default=True)),
                ('message_preview_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MESSAGE_NEW', 'Message New'), ('MESSAGE_MENTION', 'Message Mention'), ('CALL_INCOMING', 'Call Incoming'), ('CALL_MISSED', 'Call Missed'), ('DEVICE_NEW', 'Device New'), ('SYSTEM', 'System')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('collapse_key', models.CharField(blank=True, default='', max_length=128)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'), models.Index(fields=['user', 'read_at'], name='notif_user_read_idx'), models.Index(fields=['collapse_key'], name='notif_collapse_idx'), django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='notif_payload_gin')],
            },
        ),
    ]
